package es.agrobook.api.model.cultivo;

import java.util.Set;

import jakarta.persistence.*;
import lombok.*;

@Entity
@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
public class Especie {

	@Id
	private long id;

    @Column(nullable = false)
	private String descripcion;

    @Column(nullable = false)
	private boolean horticola;

    @Column(nullable = false)
	private boolean energetico;

    @Column(nullable = false)
	private boolean frutal;

    @Column(nullable = false)
	private boolean frutosCascara;

    @Column(nullable = false)
	private boolean aromaticaCondimentariaMedicinal;

    @Column(nullable = false)
	private boolean siembraDirecta;

    @Column(nullable = false)
	private boolean especiesMejorantes;

    @Column(nullable = false)
	private boolean forestalCicloCorto;

    @Column(nullable = false)
	private boolean leñosos;

    @Column(nullable = false)
	private boolean tierrasCultivo;

    @Column(nullable = false)
	private boolean cultivosPermanentes;

    @Column(nullable = false)
	private boolean pastosPermanentes;

    @Column(nullable = false)
	private boolean forestales;

    @Column(nullable = false)
	private boolean nuevo2023;


	// Entidades enlazadas

	@OneToMany(mappedBy = "especie")
    private Set<Variedad> variedades;


	/*
	 * PENDIENTE DE COMPROBAR CORRELACIÓN DE DATOS
	 * 
	Código	Cultivo	Hortícola	Energético	Frutal	Frutos cáscara	Aromáticas, condimentarias o medicinales	Siembra directa	Especies mejorantes	Forestal ciclo corto	Leñosos	Tierras de cultivo	Cultivos permanentes	Pastos permanentes	Forestales	Nuevo 2023
	1	TRIGO BLANDO	NO	SI	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	2	ESPELTA	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	3	TRIGO DURO	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	4	MAÍZ	NO	SI	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	5	CEBADA	NO	SI	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	6	CENTENO	NO	SI	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	7	SORGO	NO	SI	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	8	AVENA	NO	SI	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	9	ALFORFÓN	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	10	MIJO	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	11	ALPISTE	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	12	TRANQUILLÓN	NO	SI	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	13	TRITICALE	NO	SI	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	14	TRITORDEUM	NO	SI	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	19	TEFF	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	20	BARBECHO TRADICIONAL	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	23	BARBECHO MEDIOAMBIENTAL	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	33	GIRASOL	NO	SI	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	34	SOJA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	35	COLZA	NO	SI	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	36	CAMELINA	NO	SI	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	40	GUISANTE	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	41	HABA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	43	ALTRAMUZ BLANCO	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	49	ALUBIA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	50	GARBANZO	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	51	LENTEJA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	52	VEZA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	53	YEROS	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	60	ALFALFA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	61	ALHOLVA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	62	PASTOS PERMANENTES DE 5 O MÁS AÑOS	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO
	63	PASTOS DE MENOS DE 5 AÑOS	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	67	ESPARCETA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	68	FESTUCA	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	69	RAYGRASS PERENNE	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	70	AGROSTIS	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	71	ARRHENATHERUM	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	72	DACTILO	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	73	FLEO	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	74	POA	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	76	ZULLA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	77	TRÉBOL	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	78	RAYGRASS ANUAL 	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	80	ARROZ	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	81	ALGODÓN	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	82	REMOLACHA	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	83	TABACO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	84	LÚPULO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	85	LINO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	86	CÁÑAMO 	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	87	CACAHUETE	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	88	CÁRTAMO	NO	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	89	CHUFA	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	90	REGALIZ	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	91	FLORES	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	92	ROMANESCU	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	96	ESPECIES AROMÁTICAS HERBÁCEAS	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	97	SETAS	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	99	PATATA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	101	OLIVO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	102	VIÑA	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	104	ALMENDRO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	105	MELOCOTONERO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	106	NECTARINO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	107	ALBARICOQUERO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	108	PERAL	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	109	MANZANO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	110	CEREZO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	111	CIRUELO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	112	NOGAL	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	113	OTROS FRUTALES	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	116	CHOPO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO
	117	CASTAÑO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	118	ESPECIES AROMÁTICAS LEÑOSAS	NO	NO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	NO	NO
	119	VIVERO - PRODUCTOR MVR	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO
	120	VIÑA - OLIVAR	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	121	BONIATO	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	122	ALGARROBO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	123	AVELLANO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	124	PISTACHO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	125	FRUTOS DE CÁSCARA	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	138	ADORMIDERA	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	139	HIERBA CINTA 	NO	SI	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	140	ABACA ALIAS MANILA 	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	141	KENAF 	NO	SI	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	142	YUTE 	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	143	SISAL	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	147	ENCINA	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	SI	NO	SI	NO
	149	ZARZAMORA 	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	151	PUERRO	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	152	PIMIENTO	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	153	MELÓN	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	154	BRÓCOLI	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	155	LECHUGA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	156	SANDÍA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	157	CEBOLLA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	158	APIO	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	159	COLIRRÁBANO	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	160	COLIFLOR	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	162	BERENJENA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	163	CALABACÍN	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	164	ALCACHOFA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	165	PEPINO	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	166	ACELGA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	167	CEBOLLETA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	168	CHALOTA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	169	AJO	SI	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	171	CHIRIVÍA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	172	REPOLLO	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	173	COL ROJA O LOMBARDA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	174	COL MILÁN O SAVOY	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	175	BERZA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	176	COL DE BRUSELAS	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	177	ENDIVIA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	178	ZANAHORIA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	179	NABO	SI	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	181	ACHICORIA	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	182	GUINDILLA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	183	ESPINACA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	184	CARDO	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	185	CALABAZA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	186	CALABAZA DEL PEREGRINO	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	187	BORRAJA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	189	ESCAROLA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	190	RÁBANO	SI	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	191	BERRO DE AGUA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	192	FRAMBUESA	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	193	HUERTA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	194	CHAMPIÑÓN	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	197	TOMATE	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	200	PAULONIA	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO
	201	PLATERINA	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	202	PARAGUAYO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	203	ENDRINO o ARAÑÓN	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	204	CLEMENTINA	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	205	SATSUMA	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	206	NARANJO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	207	LIMONERO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	208	POMELO O TORONJA	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	209	MANDARINO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	210	MANDARINO HÍBRIDO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	211	MEMBRILLO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	212	KIWI	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	213	CAQUI o PALOSANTO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	214	NÍSPERO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	215	GROSELLERO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	216	ARÁNDANO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	217	GRANADO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	218	HIGUERA	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	219	FRESA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	220	CAÑA DE AZÚCAR	NO	SI	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	222	QUINOA	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	223	MISCANTHUS	NO	SI	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	224	HUAXYACAC	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	225	EUCALIPTO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO
	226	OPUNTIA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	227	SAUCE	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO
	228	ACACIA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	229	AILANTO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	230	ROBINIA	NO	SI	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO
	231	ACACIA DE TRES ESPINAS	NO	SI	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	232	JACARANDA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	233	FITOLACA	NO	SI	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	235	JATROPHA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	236	CAÑA COMÚN 	NO	SI	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	238	ALTRAMUZ AMARILLO	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	239	ALMORTA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	240	TITARROS	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	241	MEZCLA AVENA-VEZA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	242	MEZCLA TRITICALE-VEZA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	243	MEZCLA TRIGO-VEZA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	244	MEZCLA CEBADA-VEZA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	245	MEZCLA AVENA-ZULLA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	246	MEZCLA CEBADA-ZULLA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	247	CULTIVOS MIXTOS DE ESPECIES PRATENSES	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	248	ALGARROBA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	249	ALVERJA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	250	ALBERJÓN	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	251	AJEDREA	NO	NO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	NO	NO
	252	CILANTRO	SI	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	253	ANÍS DULCE	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	254	ENELDO	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	256	VALERIANA	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	257	ARTEMISA	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	258	GENCIANA	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	259	HISOPO	NO	NO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	NO	NO
	260	HINOJO	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	261	PEREJIL	SI	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	262	AZAFRÁN	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	263	TOMILLO	NO	NO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	NO	NO
	264	ALBAHACA	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	265	MELISA O TORONJIL	NO	NO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	NO	NO
	266	MENTA	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	267	ORÉGANO	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	268	SALVIA	NO	NO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	NO	NO
	269	PERIFOLLO	SI	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	270	ESTRAGÓN	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	271	MEJORANA	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	272	CALÉNDULA	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	273	COMINO	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	274	ESTEVIA	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	275	HIPÉRICO	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	276	HIERBABUENA	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	277	VERBENA	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	278	FRUTOS DEL BOSQUE	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	279	ESPÁRRAGO	SI	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	280	TRUFA	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	281	LAVANDA	NO	NO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	NO	NO
	282	LAVANDÍN	NO	NO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	NO	NO
	283	ALCAPARRA	NO	NO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	NO	NO
	284	AJENJO	NO	NO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	NO	NO
	285	ESPLIEGO	NO	NO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	NO	NO
	286	HELICRISO	NO	NO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	NO	NO
	287	HIERBALUISA	NO	NO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	NO	NO
	288	ROMERO	NO	NO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	NO	NO
	289	SANTOLINA	NO	NO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	NO	NO
	290	ALOE VERA	NO	NO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	NO	NO
	291	CAFÉ	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	293	ROBLE	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	294	HAYA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	295	ALCORNOQUE	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	296	ABETO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	297	ENEBRO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	298	MEZCLA CEBADA-GUISANTE	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	299	MEZCLA AVENA-GUISANTE	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	300	SABINA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	301	PINSAPO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	304	COL CHINA	SI	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	305	MEZCLA AVENA-TRIGO	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	306	MEZCLA AVENA-CEBADA	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	307	MEZCLA AVENA-TRITICALE	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	308	AGRIMONIA	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	309	BARDANA	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	310	DIENTE DE LEÓN	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	311	ENULA	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	312	EQUINACEA	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	313	GINSENG	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	315	LLANTÉN	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	316	MALVAVISCO	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	317	MANZANILLA AMARGA	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	318	MANZANILLA DULCE	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	319	MILENRAMA	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	320	POLEO	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	322	ROMPEPIEDRA	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	323	TRAVALERA	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	324	VARA DE ORO	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	325	TRIGO KHORASAN	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	328	PASTO DEL SUDÁN	NO	SI	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	329	AMARANTO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	331	MORINGA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	332	MOSTAZA	NO	NO	NO	NO	SI	NO	SI	NO	NO	SI	NO	NO	NO	NO
	333	PORTAINJERTOS DE VID	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	334	BARBECHO DE BIODIVERSIDAD (INCLUYE MELÍFERAS)	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	335	CABECERA DE CULTIVO PERMANENTE	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	336	MEZCLA ALGARROBA-AVENA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	337	MEZCLA ALGARROBA-CEBADA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	338	MEZCLA RAYGRASS-VEZA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	339	MEZCLA AVENA-YEROS	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	340	MEZCLA CEBADA-YEROS	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	341	SILPHIUM	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	343	AGUACATE	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	344	MANGO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	345	CHIRIMOYO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	346	PAPAYA	NO	NO	SI	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	347	MORERA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	348	VIÑA - FRUTAL	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	349	OLIVAR - FRUTAL	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	351	CÍTRICOS HÍBRIDOS-CAQUI	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	352	NARANJO-AGUACATE	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	353	CEREZO-OLIVAR	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	354	CEREZO-ALGARROBO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	355	RICINO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	356	NARANJO AMARGO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	358	MEZCLA DE FORESTALES	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	359	HIERBA DE GUINEA	NO	NO	NO	NO	NO	SI	NO	NO	NO	SI	NO	NO	NO	NO
	360	ABEDUL	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	361	ABETO DE DOUGLAS	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	362	ACEBO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	363	ACEBUCHE	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	364	ÁLAMO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO
	365	ALANTICO o LANTISCO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	366	ALERCE	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	367	ALISO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	368	ALMÁCIGO DE CANARIAS	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	369	ALMEZ	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	370	ARCE	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	371	CARPE 	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	372	CEDRO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	373	CHAPARRO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	374	CHÍA	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	375	CIPRÉS	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	376	FRESNO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	377	MADROÑO 	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	378	OLMO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	379	PALMA CANARIA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	380	PICEA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	381	QUEJIGO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	382	REBOLLO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	383	RETAMA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	384	SERBAL	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	385	TALAYA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	386	TEJO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	387	TILO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	388	YUCA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	389	PINO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	390	HABONCILLO	SI	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	391	CEREZO DE MAHOMA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	392	MEZCLA ALUBIA-MAÍZ	NO	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	393	ESCANDA	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	394	ESCAÑA	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	395	PANIZO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	397	JUDÍA ESCARLATA	NO	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	398	RAMIO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	399	SÉSAMO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	401	CEBOLLINO	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	402	ACEDERILLA	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	403	ANÍS ESTRELLADO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	404	BOTÓN DE ORO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	405	AJOWAN	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO	NO	NO	NO
	406	CHUPAMIELES	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	409	DEDALERA O DIGITAL	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	410	CICUTA	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	411	JABONERA	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	412	MALVA COMÚN	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	413	PULMONARIA	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	414	CARDO DE FULLER	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	415	TÁRTAGO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	416	PATACA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	417	CANÓNIGO	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	418	ACEDERA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	419	BERRO HORTELANO	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	420	RUIBARBO	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	421	VERDOLAGA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	422	KIWANO	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	423	TOMATILLO	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	424	ALCACHOFA CHINA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	425	GALANGA MENOR	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	426	PEREJIL TUBEROSO	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	427	RÁBANO PICANTE	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	428	JUDÍA DE LIMA	NO	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	429	COLLEJA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	430	BERGAMOTO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	431	CIDRO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	432	LIMÓN MANDARINA	NO	NO	SI	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	433	LIMERO DULCE	NO	NO	SI	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	434	LIMÓN DULCE DEL MEDITERRÁNEO	NO	NO	SI	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	435	NARANJO MORUNO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	436	ACEROLO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	437	GUINDO	NO	NO	SI	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	438	SAUCO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	439	ESPINO AMARILLO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO
	440	PITA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	441	TÉ	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	442	MIMBRERA	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO	SI	NO
	443	BAMBÚ	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	444	ZUMAQUE	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	445	COL CRESPA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	446	SERRADELLA	NO	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	447	MEZCLA CEREAL-RAYGRASS	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	448	MEZCLA AVENA-MAÍZ	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	449	MEZCLA HABA-VEZA	NO	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	450	MEZCLA CEBADA-TRIGO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	451	MEZCLA CENTENO-TRIGO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	452	MEZCLA AVENA-MAÍZ-VEZA	NO	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	453	MEZCLA CEBADA-MAÍZ-VEZA	NO	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	454	MEZCLA ALTRAMUZ-AVENA	NO	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	455	MEZCLA AVENA-CENTENO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	456	MEZCLA CENTENO-MAÍZ	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	457	MEZCLA MAÍZ-SORGO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	458	MARALFALFA	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	459	TEDERA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	460	CAUPÍ 	NO	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	461	MELILOTO AMARILLO 	NO	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	462	OJO DE BUEY	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	463	CHOISUM	SI	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	464	BRÓCOLI CHINO	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	465	BATATA ACUÁTICA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	466	CEBOLLINO CHINO	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	467	LEMONGRASS	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	468	ESPINACA DE MALABAR	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	469	LUFFA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	470	JUDÍA DE EGIPTO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	471	CALABAZA AMARGA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	472	PEPINO CULEBRA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	473	CALABAZA CHINA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	474	AROS EGIPCIOS	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	475	RÁBANO SILVESTRE	SI	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	477	SALSIFÍ	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	478	COLINABO	SI	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	479	ESCORZONERA	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	480	BARBAREA	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	481	NUEZ DE COLA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	482	ALTRAMUZ AZUL	NO	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	483	VEZA VELLOSA	NO	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	484	GRELOS	SI	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	485	BAYAS DE GOJI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	486	ALVERJA HÚNGARA	NO	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	487	CALIFORNIA BLUEBELL	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	488	BISERRULA	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	489	GRAMA COMÚN	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	490	MEDICAGO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	491	ESPIGUILLA DE BURRO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	492	AÑIL	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	493	ÍNDIGO CHINO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	494	VIÑA - HUERTA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO
	495	FRUTAL - HUERTA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO
	496	MEZCLA RAYGRASS-TRÉBOL	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	497	APIO-RÁBANO	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	498	BROCCOLINI	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	904	CROTALARIA JUNCEA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	905	PLATANERA	NO	NO	SI	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	906	PIÑA	NO	NO	SI	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	907	AZUFAIFO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	908	CARAMBOLO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	909	NASHI	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	910	LITCHI	NO	NO	SI	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	911	KUMQUAT	NO	NO	SI	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	912	LIMEQUAT	NO	NO	SI	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	913	MANO DE BUDA	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	914	CAVIAR CÍTRICO/ FINGER LIME	NO	NO	SI	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	915	LIMA	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	916	KALE	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	918	ARGÁN	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	919	PITAYA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	920	LONGAN	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	921	MANGOSTÁN	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	922	RAMBUTÁN	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	923	GUAYABO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	924	ZAPOTE	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	925	ALFICOZ	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	926	BATATA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	927	OKRA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	928	PHYSALIS	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	929	RÚCULA	SI	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	930	SALICORNIA	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	932	PLANTAS ORNAMENTALES	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	933	ÑAME	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	936	TAGASASTE	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	937	CUERNECILLO 	NO	NO	NO	NO	NO	NO	SI	NO	NO	SI	NO	NO	NO	NO
	938	FRESÓN	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO
	939	ALMENDRO-OLIVAR	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	940	NARANJO-CAQUI	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	941	NARANJO-MANDARINO	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	942	NÍSPERO-CAQUI	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	943	PALMERA DATILERA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	944	MARACUYÁ o FRUTO DE LA PASIÓN	NO	NO	SI	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	945	MEZCLA AVENA-HABA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	946	MEZCLA AVENA-CEBADA-VEZA	NO	NO	NO	NO	NO	SI	SI	NO	NO	SI	NO	NO	NO	NO
	947	JOJOBA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO
	948	CLEMENTINA-CAQUI	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	949	SATSUMA-CAQUI	NO	NO	SI	NO	NO	NO	NO	NO	SI	NO	SI	NO	NO	NO
	950	CÚRCUMA	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO
	951	JENGIBRE	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO	NO
	952	COL PICUDA	SI	NO	NO	NO	NO	NO	NO	NO	NO	SI	NO	NO	NO	NO

	
	
	 Código Especie	Especie
	1	TRIGO BLANDO
	2	ESPELTA
	3	TRIGO DURO
	4	MAÍZ
	5	CEBADA
	6	CENTENO
	7	SORGO
	8	AVENA
	9	ALFORFÓN
	10	MIJO
	11	ALPISTE
	12	TRANQUILLÓN
	13	TRITICALE
	14	TRITORDEUM
	19	TEFF
	20	BARBECHO TRADICIONAL
	23	BARBECHO MEDIOAMBIENTAL
	33	GIRASOL
	34	SOJA
	35	COLZA
	36	CAMELINA
	40	GUISANTE
	41	HABA
	43	ALTRAMUZ BLANCO
	49	ALUBIA
	50	GARBANZO
	51	LENTEJA
	52	VEZA
	53	YEROS
	60	ALFALFA
	61	ALHOLVA
	62	PASTOS PERMANENTES DE 5 O MÁS AÑOS
	63	PASTOS DE MENOS DE 5 AÑOS
	67	ESPARCETA
	68	FESTUCA
	69	RAYGRASS PERENNE
	70	AGROSTIS
	71	ARRHENATHERUM
	72	DACTILO
	73	FLEO
	74	POA
	76	ZULLA
	77	TRÉBOL
	78	RAYGRASS ANUAL 
	80	ARROZ
	81	ALGODÓN
	82	REMOLACHA
	83	TABACO
	84	LÚPULO
	85	LINO
	86	CÁÑAMO 
	87	CACAHUETE
	88	CÁRTAMO
	89	CHUFA
	90	REGALIZ
	91	FLORES
	92	ROMANESCU
	96	ESPECIES AROMÁTICAS HERBÁCEAS
	97	SETAS
	99	PATATA
	101	OLIVO
	102	VIÑA
	104	ALMENDRO
	105	MELOCOTONERO
	106	NECTARINO
	107	ALBARICOQUERO
	108	PERAL
	109	MANZANO
	110	CEREZO
	111	CIRUELO
	112	NOGAL
	113	OTROS FRUTALES
	116	CHOPO
	117	CASTAÑO
	118	ESPECIES AROMÁTICAS LEÑOSAS
	119	VIVERO - PRODUCTOR MVR
	120	VIÑA - OLIVAR
	121	BONIATO
	122	ALGARROBO
	123	AVELLANO
	124	PISTACHO
	125	FRUTOS DE CÁSCARA
	138	ADORMIDERA
	139	HIERBA CINTA 
	140	ABACA ALIAS MANILA 
	141	KENAF 
	142	YUTE 
	143	SISAL
	147	ENCINA
	149	ZARZAMORA 
	151	PUERRO
	152	PIMIENTO
	153	MELÓN
	154	BRÓCOLI
	155	LECHUGA
	156	SANDÍA
	157	CEBOLLA
	158	APIO
	159	COLIRRÁBANO
	160	COLIFLOR
	162	BERENJENA
	163	CALABACÍN
	164	ALCACHOFA
	165	PEPINO
	166	ACELGA
	167	CEBOLLETA
	168	CHALOTA
	169	AJO
	171	CHIRIVÍA
	172	REPOLLO
	173	COL ROJA O LOMBARDA
	174	COL MILÁN O SAVOY
	175	BERZA
	176	COL DE BRUSELAS
	177	ENDIVIA
	178	ZANAHORIA
	179	NABO
	181	ACHICORIA
	182	GUINDILLA
	183	ESPINACA
	184	CARDO
	185	CALABAZA
	186	CALABAZA DEL PEREGRINO
	187	BORRAJA
	189	ESCAROLA
	190	RÁBANO
	191	BERRO DE AGUA
	192	FRAMBUESA
	193	HUERTA
	194	CHAMPIÑÓN
	197	TOMATE
	200	PAULONIA
	201	PLATERINA
	202	PARAGUAYO
	203	ENDRINO o ARAÑÓN
	204	CLEMENTINA
	205	SATSUMA
	206	NARANJO
	207	LIMONERO
	208	POMELO O TORONJA
	209	MANDARINO
	210	MANDARINO HÍBRIDO
	211	MEMBRILLO
	212	KIWI
	213	CAQUI o PALOSANTO
	214	NÍSPERO
	215	GROSELLERO
	216	ARÁNDANO
	217	GRANADO
	218	HIGUERA
	219	FRESA
	220	CAÑA DE AZÚCAR
	222	QUINOA
	223	MISCANTHUS
	224	HUAXYACAC
	225	EUCALIPTO
	226	OPUNTIA
	227	SAUCE
	228	ACACIA
	229	AILANTO
	230	ROBINIA
	231	ACACIA DE TRES ESPINAS
	232	JACARANDA
	233	FITOLACA
	235	JATROPHA
	236	CAÑA COMÚN 
	238	ALTRAMUZ AMARILLO
	239	ALMORTA
	240	TITARROS
	241	MEZCLA AVENA-VEZA
	242	MEZCLA TRITICALE-VEZA
	243	MEZCLA TRIGO-VEZA
	244	MEZCLA CEBADA-VEZA
	245	MEZCLA AVENA-ZULLA
	246	MEZCLA CEBADA-ZULLA
	247	CULTIVOS MIXTOS DE ESPECIES PRATENSES
	248	ALGARROBA
	249	ALVERJA
	250	ALBERJÓN
	251	AJEDREA
	252	CILANTRO
	253	ANÍS DULCE
	254	ENELDO
	256	VALERIANA
	257	ARTEMISA
	258	GENCIANA
	259	HISOPO
	260	HINOJO
	261	PEREJIL
	262	AZAFRÁN
	263	TOMILLO
	264	ALBAHACA
	265	MELISA O TORONJIL
	266	MENTA
	267	ORÉGANO
	268	SALVIA
	269	PERIFOLLO
	270	ESTRAGÓN
	271	MEJORANA
	272	CALÉNDULA
	273	COMINO
	274	ESTEVIA
	275	HIPÉRICO
	276	HIERBABUENA
	277	VERBENA
	278	FRUTOS DEL BOSQUE
	279	ESPÁRRAGO
	280	TRUFA
	281	LAVANDA
	282	LAVANDÍN
	283	ALCAPARRA
	284	AJENJO
	285	ESPLIEGO
	286	HELICRISO
	287	HIERBALUISA
	288	ROMERO
	289	SANTOLINA
	290	ALOE VERA
	291	CAFÉ
	293	ROBLE
	294	HAYA
	295	ALCORNOQUE
	296	ABETO
	297	ENEBRO
	298	MEZCLA CEBADA-GUISANTE
	299	MEZCLA AVENA-GUISANTE
	300	SABINA
	301	PINSAPO
	304	COL CHINA
	305	MEZCLA AVENA-TRIGO
	306	MEZCLA AVENA-CEBADA
	307	MEZCLA AVENA-TRITICALE
	308	AGRIMONIA
	309	BARDANA
	310	DIENTE DE LEÓN
	311	ENULA
	312	EQUINACEA
	313	GINSENG
	315	LLANTÉN
	316	MALVAVISCO
	317	MANZANILLA AMARGA
	318	MANZANILLA DULCE
	319	MILENRAMA
	320	POLEO
	322	ROMPEPIEDRA
	323	TRAVALERA
	324	VARA DE ORO
	325	TRIGO KHORASAN
	328	PASTO DEL SUDÁN
	329	AMARANTO
	331	MORINGA
	332	MOSTAZA
	333	PORTAINJERTOS DE VID
	334	BARBECHO DE BIODIVERSIDAD (INCLUYE MELÍFERAS)
	335	CABECERA DE CULTIVO PERMANENTE
	336	MEZCLA ALGARROBA-AVENA
	337	MEZCLA ALGARROBA-CEBADA
	338	MEZCLA RAYGRASS-VEZA
	339	MEZCLA AVENA-YEROS
	340	MEZCLA CEBADA-YEROS
	341	SILPHIUM
	343	AGUACATE
	344	MANGO
	345	CHIRIMOYO
	346	PAPAYA
	347	MORERA
	348	VIÑA - FRUTAL
	349	OLIVAR - FRUTAL
	351	CÍTRICOS HÍBRIDOS-CAQUI
	352	NARANJO-AGUACATE
	353	CEREZO-OLIVAR
	354	CEREZO-ALGARROBO
	355	RICINO
	356	NARANJO AMARGO
	358	MEZCLA DE FORESTALES
	359	HIERBA DE GUINEA
	360	ABEDUL
	361	ABETO DE DOUGLAS
	362	ACEBO
	363	ACEBUCHE
	364	ÁLAMO
	365	ALANTICO o LANTISCO
	366	ALERCE
	367	ALISO
	368	ALMÁCIGO DE CANARIAS
	369	ALMEZ
	370	ARCE
	371	CARPE 
	372	CEDRO
	373	CHAPARRO
	374	CHÍA
	375	CIPRÉS
	376	FRESNO
	377	MADROÑO 
	378	OLMO
	379	PALMA CANARIA
	380	PICEA
	381	QUEJIGO
	382	REBOLLO
	383	RETAMA
	384	SERBAL
	385	TALAYA
	386	TEJO
	387	TILO
	388	YUCA
	389	PINO
	390	HABONCILLO
	391	CEREZO DE MAHOMA
	392	MEZCLA ALUBIA-MAÍZ
	393	ESCANDA
	394	ESCAÑA
	395	PANIZO
	397	JUDÍA ESCARLATA
	398	RAMIO
	399	SÉSAMO
	401	CEBOLLINO
	402	ACEDERILLA
	403	ANÍS ESTRELLADO
	404	BOTÓN DE ORO
	405	AJOWAN
	406	CHUPAMIELES
	409	DEDALERA O DIGITAL
	410	CICUTA
	411	JABONERA
	412	MALVA COMÚN
	413	PULMONARIA
	414	CARDO DE FULLER
	415	TÁRTAGO
	416	PATACA
	417	CANÓNIGO
	418	ACEDERA
	419	BERRO HORTELANO
	420	RUIBARBO
	421	VERDOLAGA
	422	KIWANO
	423	TOMATILLO
	424	ALCACHOFA CHINA
	425	GALANGA MENOR
	426	PEREJIL TUBEROSO
	427	RÁBANO PICANTE
	428	JUDÍA DE LIMA
	429	COLLEJA
	430	BERGAMOTO
	431	CIDRO
	432	LIMÓN MANDARINA
	433	LIMERO DULCE
	434	LIMÓN DULCE DEL MEDITERRÁNEO
	435	NARANJO MORUNO
	436	ACEROLO
	437	GUINDO
	438	SAUCO
	439	ESPINO AMARILLO
	440	PITA
	441	TÉ
	442	MIMBRERA
	443	BAMBÚ
	444	ZUMAQUE
	445	COL CRESPA
	446	SERRADELLA
	447	MEZCLA CEREAL-RAYGRASS
	448	MEZCLA AVENA-MAÍZ
	449	MEZCLA HABA-VEZA
	450	MEZCLA CEBADA-TRIGO
	451	MEZCLA CENTENO-TRIGO
	452	MEZCLA AVENA-MAÍZ-VEZA
	453	MEZCLA CEBADA-MAÍZ-VEZA
	454	MEZCLA ALTRAMUZ-AVENA
	455	MEZCLA AVENA-CENTENO
	456	MEZCLA CENTENO-MAÍZ
	457	MEZCLA MAÍZ-SORGO
	458	MARALFALFA
	459	TEDERA
	460	CAUPÍ 
	461	MELILOTO AMARILLO 
	462	OJO DE BUEY
	463	CHOISUM
	464	BRÓCOLI CHINO
	465	BATATA ACUÁTICA
	466	CEBOLLINO CHINO
	467	LEMONGRASS
	468	ESPINACA DE MALABAR
	469	LUFFA
	470	JUDÍA DE EGIPTO
	471	CALABAZA AMARGA
	472	PEPINO CULEBRA
	473	CALABAZA CHINA
	474	AROS EGIPCIOS
	475	RÁBANO SILVESTRE
	477	SALSIFÍ
	478	COLINABO
	479	ESCORZONERA
	480	BARBAREA
	481	NUEZ DE COLA
	482	ALTRAMUZ AZUL
	483	VEZA VELLOSA
	484	GRELOS
	485	BAYAS DE GOJI
	486	ALVERJA HÚNGARA
	487	CALIFORNIA BLUEBELL
	488	BISERRULA
	489	GRAMA COMÚN
	490	MEDICAGO
	491	ESPIGUILLA DE BURRO
	492	AÑIL
	493	ÍNDIGO CHINO
	494	VIÑA - HUERTA
	495	FRUTAL - HUERTA
	496	MEZCLA RAYGRASS-TRÉBOL
	497	APIO-RÁBANO
	498	BROCCOLINI
	904	CROTALARIA JUNCEA
	905	PLATANERA
	906	PIÑA
	907	AZUFAIFO
	908	CARAMBOLO
	909	NASHI
	910	LITCHI
	911	KUMQUAT
	912	LIMEQUAT
	913	MANO DE BUDA
	914	CAVIAR CÍTRICO/ FINGER LIME
	915	LIMA
	916	KALE
	918	ARGÁN
	919	PITAYA
	920	LONGAN
	921	MANGOSTÁN
	922	RAMBUTÁN
	923	GUAYABO
	924	ZAPOTE
	925	ALFICOZ
	926	BATATA
	927	OKRA
	928	PHYSALIS
	929	RÚCULA
	930	SALICORNIA
	932	PLANTAS ORNAMENTALES
	933	ÑAME
	936	TAGASASTE
	937	CUERNECILLO 
	938	FRESÓN
	939	ALMENDRO-OLIVAR
	940	NARANJO-CAQUI
	941	NARANJO-MANDARINO
	942	NÍSPERO-CAQUI
	943	PALMERA DATILERA
	944	MARACUYÁ o FRUTO DE LA PASIÓN
	945	MEZCLA AVENA-HABA
	946	MEZCLA AVENA-CEBADA-VEZA
	947	JOJOBA
	948	CLEMENTINA-CAQUI
	949	SATSUMA-CAQUI
	950	CÚRCUMA
	951	JENGIBRE
	952	COL PICUDA






	
	 */

}